Revert "Forbid clippy warnings"
This reverts commit 1a53d7453469dae75c20418a3f98fc184ce62f08.

1 | #![cfg_attr(feature = "cargo-clippy", deny(clippy::all))]
  |                                            ^^^^^^^^^^^
error[E0658]: scoped lint `clippy::all` is experimental (see issue #44690)